language: ruby

addons:
  postgresql: '9.4'
  mysql: '5.7'

before_install:
  # install older versions of rubygems and bundler only on Ruby < 2.7
  - if [ `echo "${TRAVIS_RUBY_VERSION:0:3} < 2.7" | bc` == 1 ]; then gem i rubygems-update -v '<3' && update_rubygems; fi;
  - if [ `echo "${TRAVIS_RUBY_VERSION:0:3} < 2.7" | bc` == 1 ]; then gem i bundler -v '<2'; fi;
  - sudo service mysql restart


cache: bundler

env:
  matrix:
    - DB=sqlite3
    - DB=mysql
    - DB=postgresql

rvm:
  - 2.6.3

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile

sudo: false

dist: xenial

matrix:
  include:
    - rvm: 2.7.1
      gemfile: gemfiles/rails_60.gemfile
      env: DB=postgresql
    - rvm: 2.6.3
      gemfile: gemfiles/rails_edge.gemfile
      env: DB=postgresql
    - rvm: 2.5.5
      gemfile: gemfiles/rails_51.gemfile
      env: DB=postgresql
    - rvm: 2.4.6
      gemfile: gemfiles/rails_50.gemfile
      env: DB=postgresql
    - rvm: 2.3.8
      gemfile: gemfiles/rails_41.gemfile
      env: DB=postgresql
    - rvm: 2.3.8
      gemfile: gemfiles/rails_40.gemfile
      env: DB=postgresql
    - rvm: 2.2.10
      gemfile: gemfiles/rails_52.gemfile
      env: DB=postgresql
    - rvm: 2.1.10
      gemfile: gemfiles/rails_42.gemfile
      env: DB=postgresql
    - rvm: 2.0.0
      gemfile: gemfiles/rails_42.gemfile
      env: DB=postgresql

  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
